### PR TITLE
flake(conduwuit): unpin crane as the toml bug has been fixed

### PR DESCRIPTION
**Pull request by girlbossceo**
### :fish: What?

Unpins `crane` from flake.nix for conduwuit builds

### :fishing_pole_and_fish: Why?

The TOML mangle bug has been fixed:

https://github.com/girlbossceo/conduwuit/pull/298
https://github.com/ipetkov/crane/issues/527#issuecomment-2067882206

### CODE REVIEW

**Review by PedroHLC — APPROVED** [review]
Thank you very much for coming all the way here to update.

**Comment by girlbossceo** [comment]
@PedroHLC I saw the CI failed for the same TOML error. Is it not pulling the right crane version?

It's definitely fixed and released here: https://github.com/ipetkov/crane/blob/master/CHANGELOG.md#0164---2024-04-07

**Comment by PedroHLC** [comment]
Failed to load source for `ruma`, caused by a TOML parse error.

**Comment by PedroHLC** [comment]
So, their FlakeHub release was stuck. They fixed it now.

**Comment by girlbossceo** [comment]
Awesome!

**Pull request merged**
