### PR TITLE
godot4-mono: init at 4.3-stable

### PR DESCRIPTION
**Pull request by dr460nf1r3**
### :fish: What?

Added `godot_4-mono`, since the package is not available in Nixpkgs yet, nor is the original PR updated. Lets add it until we have a working upstream package.

https://github.com/NixOS/nixpkgs/pull/285941
 
### :fishing_pole_and_fish: Why?

It is a very relevant package for a friend of mine, and me. 

### :fish_cake: Pending

- [x] Complain with linter.
- [x] Build package
- [x] Test package
- [x] Fix error "Unable to load .NET runtime, specifically hostfxr."
- [x] Provide `msbuild` and `dotnet-sdk` via Wrapper

### CODE REVIEW

**Review by PedroHLC — APPROVED** [review]

**Comment by GameDungeon** [comment]
One quick question, I've had issues getting the Godot-mono to run properly from a flake without a full fhs. If you have one, could you send a working flake that uses this one?

**Comment by dr460nf1r3** [comment]
This is, in fact, a flake providing this package in a working way :) or am I understanding you in a wrong way?

**Comment by GameDungeon** [comment]
Nevermind that, I misunderstood how this worked. I got nyx working, but the build for this package fails.

```
error: builder for '/nix/store/7nv7r2cafjxcsgh63d533a18xkvw73zr-godot_4-mono-4.3-stable.drv' failed with exit code 1;
       last 10 log lines:
       > /build/source/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/build/source/modules/mono/glue/GodotSharp/GodotSharp.sln]
       > /build/source/modules/mono/glue/GodotSharp/GodotPlugins/GodotPlugins.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/build/source/modules/mono/glue/GodotSharp/GodotSharp.sln]
       > /build/source/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/build/source/modules/mono/glue/GodotSharp/GodotSharp.sln]
       > /build/source/modules/mono/glue/GodotSharp/GodotPlugins/GodotPlugins.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/build/source/modules/mono/glue/GodotSharp/GodotSharp.sln]
       >   Failed to restore /build/source/modules/mono/glue/GodotSharp/GodotPlugins/GodotPlugins.csproj (in 16.33 sec).
       >   Failed to restore /build/source/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj (in 16.33 sec).
       > /build/source/modules/mono/glue/GodotSharp/Godot.SourceGenerators.Internal/Godot.SourceGenerators.Internal.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/build/source/modules/mono/glue/GodotSharp/GodotSharp.sln]
       > /build/source/modules/mono/glue/GodotSharp/Godot.SourceGenerators.Internal/Godot.SourceGenerators.Internal.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/build/source/modules/mono/glue/GodotSharp/GodotSharp.sln]
       > /build/source/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/build/source/modules/mono/glue/GodotSharp/GodotSharp.sln]
       >   Failed to restore /build/source/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj (in 33.11 sec).
       For full logs, run 'nix log /nix/store/7nv7r2cafjxcsgh63d533a18xkvw73zr-godot_4-mono-4.3-stable.drv'.
error: 1 dependencies of derivation '/nix/store/l4kajfzg2bfg8awnf07dcipfw0qgxldg-nix-shell-env.drv' failed to build
```

**Comment by dr460nf1r3** [comment]
This is interesting - have you set it up the way it is described in the README? You should not have to build the package yourself, it is available via our cache. Best guess I have right now is setting up the flake + it's module first, and then adding the package to your packages. And make sure not to override Nyx's nixpkgs to ensure profiting of the cache.

**Pull request merged**
