### PR TITLE
Bump scx_rusty from 0.0.7 to 1.0.0 stable.

### PR DESCRIPTION
**Pull request by HippieMitch**
Bumped package scx_rusty from 0.0.7 to 1.0.0 :

scx_rusty has just had its first stable release upstreamed three days ago, 1.0.0.  I personally would like to use this on my NixOS machine.  This is my first time making a PR.  If there is anything else needed to get this to build and eventually merged, please let me know.

- I like chocolate cake.

### CODE REVIEW

**Comment by PedroHLC** [comment]
Sadly, this one needs an entire bump of the SCX-package.

I'll be trying to do this bump my own after I finish rounding everything in #802. But if you want to really try it yourself, there is an unfinished updated script in `pkgs/scx/update.sh`, by the end it bumps a commit that should match the v1.0.0 tag, there is also `pkgs/scx/common.nix` to update. Then you can test everything with `nix build -L .#scx`

**Comment by HippieMitch** [comment]
Thanks.  That is useful info.  I've got it building on my machine now following your instructions.  I'll see if I can update this PR if it's successful.

**Comment by HippieMitch** [comment]
Blah, it was close I think.  Got a Meson error: 

       > Message: Fetching bpftool repo
       >
       > meson.build:186:2: ERROR: Command `/build/source/meson-scripts/fetch_bpftool /build/source/build 77a72987353fcae8ce330fd87d4c7afb7677a169` failed with status 1.

[log.txt](https://github.com/user-attachments/files/16240616/log.txt)

**Comment by HippieMitch** [comment]
I closed this because scx 1.0.1 is out already ha.  I'll create a new PR with just the scx 1.0.1 version bump.  It did look like the build service was able to make it work for 1.0.0.

**Comment by HippieMitch** [comment]
I closed this because of the scx 1.0.1 version bump.  I was gonna create a new PR, but it looks like that was the only change.

**Pull request closed without merging**
