### PR TITLE
linux-cachyos-server: init

### LINKED ISSUE #423: [Request] cachyos-server
### Link to the package upstream website/repository

[cachyos-server](https://github.com/CachyOS/linux-cachyos/tree/master/linux-cachyos-server)

### Utility this package has for you

I like cachyos kernel a lot, and would like to be able use it on servers (regular cachyos kernel is tailored for desktop/gaming more).

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

_No response_

### PR DESCRIPTION
**Pull request by Diamondy4**
### :fish: What?

1. Add the "linux-cachyos-server" kernel flavor.

### :fishing_pole_and_fish: Why?

- Closes #423

### CODE REVIEW

**Review by PedroHLC — APPROVED** [review]
Looks good to me, I'll update it all before building tough.

**Comment by PedroHLC** [comment]
@ptr1337 after updating it, I diffed the config, and there is absolutely no difference between cachyos and cachyos-server, is it only different in the PKGBUILD?

**Comment by Diamondy4** [comment]
@PedroHLC Looks like it (and .SRCINFO). Diffed linux-cachyos and linux-cachyos-server folders in original cachyos kernel repo. Basically different scheduler with some more tweaks. Maybe there would be more changes later 🤔.

<details>
<summary>Diff here</summary>

 ```diff
❯ diff -bur linux-cachyos linux-cachyos-server
diff '--color=auto' -bur linux-cachyos/PKGBUILD linux-cachyos-server/PKGBUILD
--- linux-cachyos/PKGBUILD	2023-11-09 01:34:35.391126470 +0300
+++ linux-cachyos-server/PKGBUILD	2023-11-09 01:34:35.389126414 +0300
@@ -7,7 +7,7 @@
 # Set these variables to ANYTHING that is not null or choose proper variable to enable them
 
 ### Selecting CachyOS config
-_cachy_config=${_cachy_config-y}
+_cachy_config=${_cachy_config-}
 
 ### Selecting the CPU scheduler
 # ATTENTION - one of six predefined values should be selected!
@@ -21,7 +21,7 @@
 # 'rt' - select EEVDF, but includes a series of realtime patches
 # 'rt-bore' - select Burst-Oriented Response Enhancer, but includes a series of realtime patches
 # 'sched-ext' - select 'sched-ext' Scheduler, based on EEVDF
-_cpusched=${_cpusched-cachyos}
+_cpusched=${_cpusched-eevdf}
 
 
 ### Tweak kernel options prior to a build via nconfig
@@ -75,14 +75,14 @@
 _tcp_bbr3=${_tcp_bbr3-y}
 
 ### Running with a 1000HZ, 750Hz, 600 Hz, 500Hz, 300Hz, 250Hz and 100Hz tick rate
-_HZ_ticks=${_HZ_ticks-500}
+_HZ_ticks=${_HZ_ticks-300}
 
 ## Choose between perodic, idle or full
 ### Full tickless can give higher performances in various cases but, depending on hardware, lower consistency.
-_tickrate=${_tickrate-full}
+_tickrate=${_tickrate-idle}
 
 ## Choose between full(low-latency), voluntary or server
-_preempt=${_preempt-full}
+_preempt=${_preempt-server}
 
 ### Enable multigenerational LRU
 # ATTENTION - one of three predefined values should be selected!
@@ -104,10 +104,10 @@
 # 'madvise' - madvise, prevent applications from allocating more memory resources than necessary
 # More infos here:
 # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/performance_tuning_guide/sect-red_hat_enterprise_linux-performance_tuning_guide-configuring_transparent_huge_pages
-_hugepage=${_hugepage-always}
+_hugepage=${_hugepage-madvise}
 
 ## Enable DAMON
-_damon=${_damon-}
+_damon=${_damon-y}
 
 ## Enable Linux Random Number Generator
 _lrng_enable=${_lrng_enable-}
@@ -162,11 +162,11 @@
 _bcachefs=${_bcachefs-}
 
 if [[ "$_use_llvm_lto" = "thin" || "$_use_llvm_lto" = "full" ]] && [ -n "$_use_lto_suffix" ]; then
-    pkgsuffix=cachyos-lto
+    pkgsuffix=cachyos-server-lto
     pkgbase=linux-$pkgsuffix
 
 else
-    pkgsuffix=cachyos
+    pkgsuffix=cachyos-server
     pkgbase=linux-$pkgsuffix
 fi
 _major=6.6
@@ -179,7 +179,7 @@
 #_stablerc=${_major}-${_rcver}
 _srcname=linux-${_stable}
 #_srcname=linux-${_major}
-pkgdesc='Linux EEVDF-BORE scheduler Kernel by CachyOS with other patches and improvements'
+pkgdesc='Linux EEVDF scheduler Kernel by CachyOS targeted for Servers'
 pkgrel=2
 _kernver=$pkgver-$pkgrel
 arch=('x86_64' 'x86_64_v3')
@@ -868,5 +868,4 @@
 b2sums=('5f02fd8696d42f7ec8c5fbadec8e7270bdcfcb1f9844a6c4db3e1fd461c93ce1ccda650ca72dceb4890ebcbbf768ba8fba0bce91efc49fbd2c307b04e95665f2'
         '98efc768a2048843086a0a0ee495d992b615fcc0dc3003f71e9828a2595dde2be0302739d99d84fdae69531be4f0a3277328b06985f40e811593764e907257aa'
         '11d2003b7d71258c4ca71d71c6b388f00fe9a2ddddc0270e304148396dadfd787a6cac1363934f37d0bfb098c7f5851a02ecb770e9663ffe57ff60746d532bd0'
-        'b99458e40605388759bfc3d07233acb5ae29c4c0ff3b10c2532f11a5a946a752ec1a654ba2a51670afc415e90ac2ce48a24c0977a92fe8acf691345171d95924'
-        'caedeef9cf148961a2fc1a06f175682c401448276e57921221c54ffaf7b27135de9d6b8e22f12cdc14b31a042493ffc8970211d68819264d202b811cd7db0c36')
+        'b99458e40605388759bfc3d07233acb5ae29c4c0ff3b10c2532f11a5a946a752ec1a654ba2a51670afc415e90ac2ce48a24c0977a92fe8acf691345171d95924')
diff '--color=auto' -bur linux-cachyos/.SRCINFO linux-cachyos-server/.SRCINFO
--- linux-cachyos/.SRCINFO	2023-11-09 01:34:35.391126470 +0300
+++ linux-cachyos-server/.SRCINFO	2023-11-09 01:34:35.389126414 +0300
@@ -1,7 +1,7 @@
 # Generated by makepkg 6.0.2
-# Mon Nov  6 19:42:47 UTC 2023
-pkgbase = linux-cachyos
-	pkgdesc = Linux EEVDF-BORE scheduler Kernel by CachyOS with other patches and improvements
+# Mon Nov  6 19:44:50 UTC 2023
+pkgbase = linux-cachyos-server
+	pkgdesc = Linux EEVDF scheduler Kernel by CachyOS targeted for Servers
 	pkgver = 6.6.0
 	pkgrel = 2
 	url = https://github.com/CachyOS/linux-cachyos
@@ -28,15 +28,13 @@
 	source = config
 	source = auto-cpu-optimization.sh
 	source = https://raw.githubusercontent.com/cachyos/kernel-patches/master/6.6/all/0001-cachyos-base-all.patch
-	source = https://raw.githubusercontent.com/cachyos/kernel-patches/master/6.6/sched/0001-bore-cachy.patch
 	b2sums = 5f02fd8696d42f7ec8c5fbadec8e7270bdcfcb1f9844a6c4db3e1fd461c93ce1ccda650ca72dceb4890ebcbbf768ba8fba0bce91efc49fbd2c307b04e95665f2
 	b2sums = 98efc768a2048843086a0a0ee495d992b615fcc0dc3003f71e9828a2595dde2be0302739d99d84fdae69531be4f0a3277328b06985f40e811593764e907257aa
 	b2sums = 11d2003b7d71258c4ca71d71c6b388f00fe9a2ddddc0270e304148396dadfd787a6cac1363934f37d0bfb098c7f5851a02ecb770e9663ffe57ff60746d532bd0
 	b2sums = b99458e40605388759bfc3d07233acb5ae29c4c0ff3b10c2532f11a5a946a752ec1a654ba2a51670afc415e90ac2ce48a24c0977a92fe8acf691345171d95924
-	b2sums = caedeef9cf148961a2fc1a06f175682c401448276e57921221c54ffaf7b27135de9d6b8e22f12cdc14b31a042493ffc8970211d68819264d202b811cd7db0c36
 
-pkgname = linux-cachyos
-	pkgdesc = The Linux EEVDF-BORE scheduler Kernel by CachyOS with other patches and improvements kernel and modules
+pkgname = linux-cachyos-server
+	pkgdesc = The Linux EEVDF scheduler Kernel by CachyOS targeted for Servers kernel and modules
 	depends = coreutils
 	depends = kmod
 	depends = initramfs
@@ -49,7 +47,7 @@
 	provides = KSMBD-MODULE
 	provides = UKSMD-BUILTIN
 
-pkgname = linux-cachyos-headers
-	pkgdesc = Headers and scripts for building modules for the Linux EEVDF-BORE scheduler Kernel by CachyOS with other patches and improvements kernel
+pkgname = linux-cachyos-server-headers
+	pkgdesc = Headers and scripts for building modules for the Linux EEVDF scheduler Kernel by CachyOS targeted for Servers kernel
 	depends = pahole
-	depends = linux-cachyos
+	depends = linux-cachyos-server

 ```


</details>

**Comment by PedroHLC** [comment]
Yeah, we need to add a structure to the flavor to extend the pkgbuildConfig, and apply these changes.

**Comment by ptr1337** [comment]
> Yeah, we need to add a structure to the flavor to extend the pkgbuildConfig, and apply these changes.

The changes are done via the PKGBUILD. Generally I think this is the most "easiest" way, to keep mostly everything equal and easy to maintain.
But it is really confusing for some people, when checking the config itself.

**Pull request merged**
