### PR TITLE
owl-wlr: init at unstable-20241209-37efc0c0d

### PR DESCRIPTION
**Pull request by s0me1newithhand7s**
### :fish: What?

1. Init `owl_git`

### :fishing_pole_and_fish: Why?

- I really wan't this package since nor river or sway actually suits me.

### :whale: Extras

- Do you like roses?

### CODE REVIEW

**Comment by s0me1newithhand7s** [comment]
i think i need redact commit message holdon xD

**Comment by s0me1newithhand7s** [comment]
> Thank you for contributing to nyx! Please run `nix fmt` on your code before submitting a pull request. Afterwards, please force push your changes.

oh ok

**Comment by s0me1newithhand7s** [comment]
i'll check it.. today, after i sleep

**Comment by s0me1newithhand7s** [comment]
oops

**Comment by s0me1newithhand7s** [comment]
heck

**Review by PedroHLC — APPROVED** [review]

**Comment by s0me1newithhand7s** [comment]
yay!

**Pull request merged**
