### PR TITLE
scx 0.1.10 > 1.0.1 version bump.

### PR DESCRIPTION
**Pull request by HippieMitch**
Bumped package scx from 0.1.10 to 1.0.1.

This started out as me just trying to update scx_rusty to 1.0.0, but we ended up needing to fully update scx.  While working on scx 1.0.0, scx 1.0.1 was released upstream.  This is my second PR regarding this due to the last one only referring to scx_rusty and not the scx package itself.

 I like chocolate cake.

### CODE REVIEW

**Comment by HippieMitch** [comment]
I'm able to build this until the "Fetching bpftool repo" error.  

> Message: Fetching bpftool repo
 > meson.build:186:2: ERROR: Command `/build/source/meson-scripts/fetch_bpftool /build/source/build 77a72987353fcae8ce330fd87d4c7afb7677a169` failed with status 1.

[Nix Build Log] (https://github.com/user-attachments/files/16242699/log.txt)

**Comment by PedroHLC** [comment]
> Clarification. I'm able to build this until the "Fetching bpftool repo" meson error.

You're almost there, just need to update "rev" to `77a72987353fcae8ce330fd87d4c7afb7677a169` and "hash" in `pkgs/scx/default.nix:54`

**Comment by HippieMitch** [comment]
Thanks for what you do and the info.

**Comment by PedroHLC** [comment]
It was in the error message you posted, and also in `meson.build`

**Comment by HippieMitch** [comment]
Aha...  😅.  Thanks again.

**Pull request merged**
