### PR TITLE
nyx-overlay: respect user's config.nixpkgs.config

### PR DESCRIPTION
**Pull request by PedroHLC**
### :fish: What?

Instead of using the flake input, import it, passing the user's config forward.

### :fishing_pole_and_fish: Why?

Fixes https://github.com/chaotic-cx/nyx/issues/142

### CODE REVIEW

**Comment by SuperSamus** [comment]
I'm now getting:

```console
       error: attribute 'system' missing

       at /nix/store/vdk6xz3qzdhrprs87vghlg53fm2k9b3i-source/modules/nyx-overlay.nix:9:42:

            8|     let
            9|       prev = import "${inputs.nixpkgs}" {
             |                                          ^
           10|         inherit (pkgs) system;
       Did you mean one of mystem, systemc, systemd, syntex or systemfd?
```

**Comment by PedroHLC** [comment]
> I'm now getting:

Can you try this, please?

```console
╰─λ cd /etc/nixos
╭─pedrohlc at desktop in /etc/nixos
╰─λ nix repl
Welcome to Nix 2.16.0. Type :? for help.

nix-repl> :lf .
Added 10 variables.

nix-repl> nixosConfigurations.desktop.pkgs.system
"x86_64-linux"
```

Just replace "desktop" with your output's name.

**Comment by SuperSamus** [comment]
Same thing:

```console
error: attribute 'system' missing

       at «string»:1:1:

            1| nixosConfigurations.nixos.pkgs.system
             | ^
       Did you mean one of mystem, systemc, systemd, syntex or systemfd?
```

Tab completion shows that `pkgs` has several attributes, but `system` is not one of them.

**Comment by PedroHLC** [comment]
> Tab completion shows that `pkgs` has several attributes, but `system` is not one of them.

Didn't except this scenario, but I was already considering moving to this, can you check if this branch works for you?:

https://github.com/chaotic-cx/nyx/tree/nyx-overlay/use-local-cross-system

**Comment by SuperSamus** [comment]
It starts building now.

**Comment by PedroHLC** [comment]
> It starts building with this branch. (Didn't test if it also finishes building.)

If it builds and boots, please approve #144.

**Pull request merged**
