### PR TITLE
flake: add homeManagerModules.default; some overall enhancements

### LINKED ISSUE #54: Add instructions for non-NixOS home-manager users
Hi, I still don't really get how to use flakes, I put in the flake configs in `~/.config/home-manager/flake.nix` and I got the following output:

```
warning: creating lock file '/home/fenglengshun/.config/home-manager/flake.lock'
error: flake 'path:/home/fenglengshun/.config/home-manager' does not provide attribute 'packages.x86_64-linux.homeConfigurations', 'legacyPackages.x86_64-linux.homeConfigurations' or 'homeConfigurations'
error: flake 'path:/home/fenglengshun/.config/home-manager' does not provide attribute 'packages.x86_64-linux.homeConfigurations', 'legacyPackages.x86_64-linux.homeConfigurations' or 'homeConfigurations'
error: flake 'path:/home/fenglengshun/.config/home-manager' does not provide attribute 'packages.x86_64-linux.homeConfigurations."fenglengshun".activationPackage', 'legacyPackages.x86_64-linux.homeConfigurations."fenglengshun".activationPackage' or 'homeConfigurations."fenglengshun".activationPackage'
```

Currently, I only understand using import \<channel\>, builtins.fetchTarball, and builtins.fetchGit. Could an example for home-manager flake config be added please? Or maybe a simpler import set-up that could be added to instructions?

### PR DESCRIPTION
**Pull request by PedroHLC**
### :fish: What?

1. refactor multiple `.overrides` usage;
2. change some packages' descriptions;
3. add home-manager module;
4. add home-manager instructions to `README.md`;
5. document home-manager options;
6. comment utils' functions.

### :fishing_pole_and_fish: Why?

- (1) I find `.override` followed by `.overrideAttrs` hideous;
- (2) Their description was wrong or incomplete;
- (3) Required for using directly with home-manager;
- (4) Closes #54;
- (5) Helps with (3) and (4).

### CODE REVIEW

**Comment by PedroHLC** [comment]
@bayazidbh in this version you won't need `extraSpecialArgs` and one advantage we forgot: you'll be able our pre-built cache.

**Review by JustTNE — APPROVED** [review]
The commit names are not the most encouraging, but I haven't spotted anything egregious! LGTM!

**Comment by PedroHLC** [comment]
> The commit names are not the most encouraging, but I haven't spotted anything egregious! LGTM!

When creating the HTML page with all the HM options, we run `homeManagerConfiguration` which evaluates these modules for us :smile: (some kind of testing).

**Comment by bayazidbh** [comment]
Hm, could I have a mistake somewhere? I have added the module, but I got the following output:

<details><summary>Details</summary>
<p>

```nix
error: attribute 'homeManagerModules' missing

       at /nix/store/1nddqfg4wcmlyy3hwrjjkic1mx12y541-source/flake.nix:56:11:

           55|           flatpaks.homeManagerModules.default # import declarative-flatpak module
           56|           chaotic.homeManagerModules.default # chaotic nyx HM module
             |           ^
           57|         ];
(use '--show-trace' to show detailed location information)
``` 

</p>
</details> 

<details><summary>trace</summary>
<p>

```nix
home-manager switch -b bak --show-trace
error:
       … while evaluating call site

       at /nix/store/hb6jsjykkkwxs4qygk81pcrmdml16xb7-source/modules/default.nix:39:12:

           38|
           39|   module = showWarnings (
             |            ^
           40|     let

       … while calling 'showWarnings'

       at /nix/store/hb6jsjykkkwxs4qygk81pcrmdml16xb7-source/modules/default.nix:18:18:

           17|
           18|   showWarnings = res:
             |                  ^
           19|     let

       … while evaluating call site

       at /nix/store/hb6jsjykkkwxs4qygk81pcrmdml16xb7-source/modules/default.nix:22:7:

           21|     in
           22|       fold f res res.config.warnings;
             |       ^
           23|

       … while calling 'foldr'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/lists.nix:53:20:

           52|   */
           53|   foldr = op: nul: list:
             |                    ^
           54|     let

       … while evaluating call site

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/lists.nix:60:8:

           59|         else op (elemAt list n) (fold' (n + 1));
           60|     in fold' 0;
             |        ^
           61|

       … while calling 'fold''

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/lists.nix:56:15:

           55|       len = length list;
           56|       fold' = n:
             |               ^
           57|         if n == len

       … while evaluating call site

       at /nix/store/hb6jsjykkkwxs4qygk81pcrmdml16xb7-source/modules/default.nix:41:16:

           40|     let
           41|       failed = collectFailed rawModule.config;
             |                ^
           42|       failedStr = concatStringsSep "\n" (map (x: "- ${x}") failed);

       … while calling 'collectFailed'

       at /nix/store/hb6jsjykkkwxs4qygk81pcrmdml16xb7-source/modules/default.nix:15:19:

           14|
           15|   collectFailed = cfg:
             |                   ^
           16|     map (x: x.message) (filter (x: !x.assertion) cfg.assertions);

       … while evaluating the attribute 'config'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:320:9:

          319|         options = checked options;
          320|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          321|         _module = checked (config._module);

       … while evaluating call site

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:242:28:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                            ^
          243|

       … while calling 'mapAttrsRecursiveCond'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/attrsets.nix:594:5:

          593|     # Attribute set to recursively map over.
          594|     set:
             |     ^
          595|     let

       … while evaluating the attribute 'matchedOptions'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:677:14:

          676|     in {
          677|       inherit matchedOptions;
             |              ^
          678|

       … while evaluating call site

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:234:33:

          233|           ({ inherit lib options config specialArgs; } // specialArgs);
          234|         in mergeModules prefix (reverseList collected);
             |                                 ^
          235|

       … while calling 'reverseList'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/lists.nix:436:17:

          435|   */
          436|   reverseList = xs:
             |                 ^
          437|     let l = length xs; in genList (n: elemAt xs (l - n - 1)) l;

       … while evaluating call site

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:229:25:

          228|       merged =
          229|         let collected = collectModules
             |                         ^
          230|           class

       … while calling anonymous lambda

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:443:37:

          442|
          443|     in modulesPath: initialModules: args:
             |                                     ^
          444|       filterModules modulesPath (collectStructuredModules unknownModule "" initialModules args);

       … while evaluating call site

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:444:7:

          443|     in modulesPath: initialModules: args:
          444|       filterModules modulesPath (collectStructuredModules unknownModule "" initialModules args);
             |       ^
          445|

       … while calling 'filterModules'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:411:36:

          410|       # modules recursively. It returns the final list of unique-by-key modules
          411|       filterModules = modulesPath: { disabled, modules }:
             |                                    ^
          412|         let

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:437:31:

          436|           disabledKeys = concatMap ({ file, disabled }: map (moduleKey file) disabled) disabled;
          437|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);
             |                               ^
          438|         in map (attrs: attrs.module) (builtins.genericClosure {

       … while evaluating the attribute 'disabled'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:393:13:

          392|           collectResults = modules: {
          393|             disabled = concatLists (catAttrs "disabled" modules);
             |             ^
          394|             inherit modules;

       … while evaluating call site

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:398:22:

          397|           let
          398|             module = checkModule (loadModule args parentFile "${parentKey}:anon-${toString n}" x);
             |                      ^
          399|             collectedImports = collectStructuredModules module._file module.key module.imports args;

       … while calling anonymous lambda

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:363:11:

          362|         else
          363|           m: m;
             |           ^
          364|

       … while evaluating call site

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:398:35:

          397|           let
          398|             module = checkModule (loadModule args parentFile "${parentKey}:anon-${toString n}" x);
             |                                   ^
          399|             collectedImports = collectStructuredModules module._file module.key module.imports args;

       … while calling 'loadModule'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:334:53:

          333|       # Like unifyModuleSyntax, but also imports paths and calls functions if necessary
          334|       loadModule = args: fallbackFile: fallbackKey: m:
             |                                                     ^
          335|         if isFunction m then

       … while evaluating call site

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/modules.nix:335:12:

          334|       loadModule = args: fallbackFile: fallbackKey: m:
          335|         if isFunction m then
             |            ^
          336|           unifyModuleSyntax fallbackFile fallbackKey (applyModuleArgs fallbackKey m args)

       … while calling 'isFunction'

       at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/trivial.nix:448:16:

          447|   */
          448|   isFunction = f: builtins.isFunction f ||
             |                ^
          449|     (f ? __functor && isFunction (f.__functor f));

       error: attribute 'homeManagerModules' missing

       at /nix/store/gpzshdyby418aykimc3m0vivgm1n7g8k-source/flake.nix:55:11:

           54|           flatpaks.homeManagerModules.default # import declarative-flatpak module
           55|           chaotic.homeManagerModules.default # chaotic nyx HM module
             |           ^
           56|         ];

``` 

</p>
</details> 

<details><summary>Flakes</summary>
<p>

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable"; # use nixpkgs-unstable as main nixpkgs source
    home-manager = {
      url = "github:nix-community/home-manager"; # home-manager unstable url
      inputs.nixpkgs.follows = "nixpkgs"; # inherit nixpkgs-unstable as main nixpkgs source
    };
    flatpaks.url = "github:GermanBread/declarative-flatpak/stable"; # declarative-flatpak, still WIP
    chaotic.url = "github:chaotic-cx/nyx/nyxpkgs-unstable"; # https://github.com/chaotic-cx/nyx#how-to-use-it}
    # Add other inputs if needed
  };

  outputs = { self, nixpkgs, home-manager, flatpaks, chaotic }:
  let

    # System types to support.  [ "x86_64-linux" "x86_64-darwin" "aarch64-linux" "aarch64-darwin" ];
    supportedSystems = [ "x86_64-linux" ];
    # Helper function to generate an attrset '{ x86_64-linux = f "x86_64-linux"; ... }'.
    forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
    # Nixpkgs instantiated for supported system types.
    nixpkgsFor = forAllSystems (system: import nixpkgs { inherit system; });

  in
  {
    # Standalone home-manager configuration entrypoint
    homeConfigurations = {
    # declare a "username" or "username@hostname" specific configuration
      "fenglengshun@ostree-pc" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
        # extraSpecialArgs = { inherit chaotic; }; # so that home-manager can correctly read chaotic.packages
        modules = [
          ./home.nix # default home.nix
          ./shell.nix # shell config for all devices
          ./env.nix # env-var for all devices
          ./alias.nix # aliases for all devices
          ./files.nix # file creation for all devices
          ./pc/by-device.nix # device specific configs
          ./pc/flatpak.nix # separate list for flatpak
          ./pc/chaotic.nix # separate list for chaotic.nix packages
          flatpaks.homeManagerModules.default # declarative-flatpak HM module
          chaotic.homeManagerModules.default # chaotic nyx HM module
        ];
      };
      "fenglengshun@neon-laptop" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
        modules = [
          ./home.nix # default home.nix
          ./shell.nix # shell config for all devices
          ./env.nix # env-var for all devices
          ./alias.nix # aliases for all devices
          ./files.nix # file creation for all devices
          ./laptop/by-device.nix # device specific configs
          ./laptop/flatpak.nix # separate list for flatpak
          ./laptop/chaotic.nix
          flatpaks.homeManagerModules.default # import declarative-flatpak module
          chaotic.homeManagerModules.default # chaotic nyx HM module
        ];
      };
    };
  };
}

```

</p>
</details> 

<details><summary>chaotic.nix</summary>
<p>

```nix
{ pkgs, ... }:
{
  home.packages = with pkgs; [
    fastfetch
  ];
}

``` 

</p>
</details>

**Comment by PedroHLC** [comment]
@bayazidbh did you `nix flake update`? (or to update only chaotic: `nix flake lock --update-input chaotic`)

**Comment by bayazidbh** [comment]
I got an error:
```
error:
       Failed assertions:
       - A corresponding Nix package must be specified via `nix.package` for generating
       nix.conf
```
I asked around in [NixOS Discord](https://discord.com/channels/568306982717751326/790886215532150815/1135764613116477470) and I think it's an issue with the module? Something about not setting `nix.package`?

**Comment by PedroHLC** [comment]
> I asked around in [NixOS Discord](https://discord.com/channels/568306982717751326/790886215532150815/1135764613116477470) and I think it's an issue with the module? Something about not setting `nix.package`?

Yeah, you just need to add `nix.package = pkgs.nix;` (for the stablest nix) or `nix.package = pkgs.nixVersions.unstable;`, to your `home.nix`.

**Comment by bayazidbh** [comment]
That works, thanks. Should probably add that to the instruction btw?

**Pull request merged**
